"""empty message

Revision ID: fe3eee3dec97
Revises: 471eb4a0b156
Create Date: 2026-05-02 00:10:54.883373

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fe3eee3dec97'
down_revision = '471eb4a0b156'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('interests_name_key'), type_='unique')

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('profiles_user_id_key'), type_='unique')

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('users_email_key'), type_='unique')
        batch_op.drop_constraint(batch_op.f('users_username_key'), type_='unique')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('users_username_key'), ['username'], postgresql_nulls_not_distinct=False)
        batch_op.create_unique_constraint(batch_op.f('users_email_key'), ['email'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('profiles', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('profiles_user_id_key'), ['user_id'], postgresql_nulls_not_distinct=False)

    with op.batch_alter_table('interests', schema=None) as batch_op:
        batch_op.create_unique_constraint(batch_op.f('interests_name_key'), ['name'], postgresql_nulls_not_distinct=False)

    # ### end Alembic commands ###
